"""Data-quality report: counts, missing fields, duplicates, rejected records,
and visual samples. Written as Markdown + JPEG contact sheets."""

from __future__ import annotations

import json
import random
import sqlite3
from collections import Counter, defaultdict
from collections.abc import Sequence
from pathlib import Path
from typing import Any

from PIL import Image, ImageDraw, ImageOps

from wildinbox.class_map import EMPTY_CLASS
from wildinbox.ingestion.inventory import (
    NEAR_DUPLICATE_MIN_SIMILARITY,
    Paths,
    Reason,
    Status,
    Warning_,
    counts,
)

THUMB = (200, 146)
PER_SHEET = 8
SEED = 0


def _table(headers: Sequence[str], rows: Sequence[Sequence[Any]]) -> str:
    out = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def _sheet(items: Sequence[tuple[Path | None, str]], out: Path, cols: int = 4) -> None:
    rows = max(1, -(-len(items) // cols))
    w, h = THUMB
    cap = 28
    sheet = Image.new("RGB", (cols * w, rows * (h + cap)), "white")
    draw = ImageDraw.Draw(sheet)
    for i, (path, caption) in enumerate(items):
        x, y = (i % cols) * w, (i // cols) * (h + cap)
        if path is not None and path.exists():
            try:
                with Image.open(path) as img:
                    sheet.paste(ImageOps.fit(img.convert("RGB"), THUMB), (x, y))
            except Exception:
                draw.rectangle([x, y, x + w - 1, y + h - 1], fill="#ccc")
                draw.text((x + 6, y + 6), "unreadable", fill="black")
        else:
            draw.rectangle([x, y, x + w - 1, y + h - 1], fill="#eee")
            draw.text((x + 6, y + 6), "missing file", fill="black")
        draw.text((x + 4, y + h + 4), caption[:34], fill="black")
    out.parent.mkdir(parents=True, exist_ok=True)
    sheet.save(out, "JPEG", quality=80)


def write_report(paths: Paths, version: str, out_dir: Path) -> Path:
    conn = sqlite3.connect(paths.database)
    conn.row_factory = sqlite3.Row
    rows = [dict(r) for r in conn.execute("SELECT * FROM records ORDER BY source_id")]
    for r in rows:
        for k in ("reasons", "warnings", "original_labels"):
            r[k] = json.loads(r[k])
    summary = counts(conn)
    rng = random.Random(SEED)
    img_dir = out_dir / "images"
    md: list[str] = []

    md += [
        f"# Data-quality report: `{version}`",
        "",
        "Generated by `wildinbox data report`. Every source record is accounted for as "
        "accepted, quarantined, or excluded.",
        "",
        "## Accounting",
        "",
        _table(
            ["", "Records"],
            [["Source records", summary["source_records"]]]
            + [[s.value, summary["by_status"][s.value]] for s in Status],
        ),
        "",
    ]
    if summary["by_reason"]:
        md += [
            "**Reasons** (a record can have more than one):",
            "",
            _table(["Reason", "Records"], list(summary["by_reason"].items())),
            "",
        ]
    md += [
        f"- Annotations referring to no image: **{summary['orphan_annotations']}**",
        f"- Image files not referenced by any metadata: **{summary['orphan_files']}**",
        "",
    ]

    # Class counts by original benchmark file
    accepted = [r for r in rows if r["status"] == Status.ACCEPTED.value]
    files = sorted({r["source_file"] for r in rows})
    short = [Path(f).stem.replace("_annotations", "") for f in files]
    by_label: dict[str, Counter[str]] = defaultdict(Counter)
    for r in accepted:
        by_label[r["normalized_label"] or "(multi-species, unlabeled)"][r["source_file"]] += 1
    label_rows = sorted(by_label.items(), key=lambda kv: -sum(kv[1].values()))
    md += [
        "## Class counts (accepted records)",
        "",
        "Columns are the published CCT20 benchmark files each record came from. "
        "Labels are `lowercase_snake(category name)`; originals are kept unchanged "
        "in the inventory.",
        "",
        _table(
            ["Label", "Total", *short],
            [[k, sum(c.values()), *(c[f] for f in files)] for k, c in label_rows],
        ),
        "",
    ]

    # Cameras
    cams: dict[str, Counter[str]] = defaultdict(Counter)
    for r in accepted:
        cams[r["camera_id"]][r["normalized_label"] or "multi"] += 1
    cam_files: dict[str, set[str]] = defaultdict(set)
    for r in rows:
        if r["camera_id"]:
            cam_files[r["camera_id"]].add(Path(r["source_file"]).stem.replace("_annotations", ""))
    md += [
        "## Cameras",
        "",
        f"{len(cams)} cameras with accepted records.",
        "",
        _table(
            ["Camera", "Images", "Empty %", "Classes", "Benchmark files"],
            [
                [
                    cam,
                    sum(c.values()),
                    f"{100 * c.get(EMPTY_CLASS, 0) / max(1, sum(c.values())):.0f}",
                    len([k for k in c if k != EMPTY_CLASS]),
                    ", ".join(sorted(cam_files[cam])),
                ]
                for cam, c in sorted(cams.items(), key=lambda kv: -sum(kv[1].values()))
            ],
        ),
        "",
    ]

    # Sequence sizes
    seq_sizes = Counter(Counter(r["sequence_id"] for r in rows if r["sequence_id"]).values())
    md += [
        "## Sequence sizes",
        "",
        _table(["Frames in sequence", "Sequences"], sorted(seq_sizes.items())),
        "",
    ]

    # Missing fields
    fields = {
        "camera (location)": "camera_id",
        "sequence id": "sequence_id",
        "timestamp": "captured_at",
        "frame number": "frame_num",
        "image file": "storage_path",
    }
    md += [
        "## Missing fields",
        "",
        _table(
            ["Field", "Records missing it"],
            [[k, sum(1 for r in rows if r[col] is None)] for k, col in fields.items()],
        ),
        "",
    ]

    # Warnings and duplicates
    warn_counts = Counter(w["code"] for r in rows for w in r["warnings"])
    dup_excluded = [
        r for r in rows if any(x["code"] == Reason.EXACT_DUPLICATE for x in r["reasons"])
    ]
    md += [
        "## Duplicates and warnings",
        "",
        f"- Exact duplicates (identical bytes) excluded: **{len(dup_excluded)}**",
        "- Suspected near-duplicates across different cameras (high-pass thumbnail "
        f"similarity >= {NEAR_DUPLICATE_MIN_SIMILARITY}): "
        f"**{summary['near_duplicate_pairs']} pairs**. Frames within one camera are expected "
        "to look alike and are not flagged, since splits hold out whole cameras.",
        "",
    ]
    if warn_counts:
        md += [
            _table(["Warning (record stays accepted)", "Records"], sorted(warn_counts.items())),
            "",
        ]

    # Rejected records
    rejected = [r for r in rows if r["status"] != Status.ACCEPTED.value]
    md += ["## Quarantined and excluded records", ""]
    if rejected:
        md += [
            _table(
                ["Source id", "Status", "Reasons", "File"],
                [
                    [
                        r["source_id"],
                        r["status"],
                        "; ".join(f"{x['code']}: {x['detail']}" for x in r["reasons"]),
                        r["file_name"],
                    ]
                    for r in rejected[:50]
                ],
            ),
            "",
        ]
        if len(rejected) > 50:
            md += [f"...and {len(rejected) - 50} more (see the manifest).", ""]
    else:
        md += ["None.", ""]
    orphans = [r[0] for r in conn.execute("SELECT storage_path FROM orphan_files LIMIT 20")]
    if orphans:
        md += ["Unreferenced image files (first 20): " + ", ".join(f"`{o}`" for o in orphans), ""]

    # Visual samples
    md += ["## Visual samples", "", "Random accepted examples per class (seed 0).", ""]
    for label, _ in label_rows:
        pool = [
            r for r in accepted if (r["normalized_label"] or "(multi-species, unlabeled)") == label
        ]
        pick = rng.sample(pool, min(PER_SHEET, len(pool)))
        name = label.strip("()").replace(",", "").replace(" ", "_")
        _sheet(
            [
                (paths.images / r["storage_path"], f"cam {r['camera_id']} {r['captured_at'] or ''}")
                for r in pick
            ],
            img_dir / f"class_{name}.jpg",
        )
        md += [f"### {label}", "", f"![{label}](images/class_{name}.jpg)", ""]

    suspicious: list[tuple[Path | None, str]] = []
    for r in rejected[:8]:
        path = paths.images / r["storage_path"] if r["storage_path"] else None
        suspicious.append((path, f"{r['status']}: {r['reasons'][0]['code']}"))
    ids = {r["source_id"]: r for r in rows}
    for a, b, d in conn.execute(
        "SELECT a, b, similarity FROM near_duplicates ORDER BY similarity DESC LIMIT 4"
    ):
        for sid in (a, b):
            r = ids[sid]
            suspicious.append(
                (paths.images / r["storage_path"], f"near-dup sim={d:.2f} cam {r['camera_id']}")
            )
    for code in (
        Warning_.ASPECT_MISMATCH,
        Warning_.MULTI_SPECIES,
        Warning_.SEQUENCE_MULTIPLE_CAMERAS,
    ):
        for r in [r for r in rows if any(w["code"] == code for w in r["warnings"])][:4]:
            path = paths.images / r["storage_path"] if r["storage_path"] else None
            suspicious.append((path, code.value))
    md += ["## Suspicious records", ""]
    if suspicious:
        _sheet(suspicious[:24], img_dir / "suspicious.jpg")
        md += [
            "Quarantined files, cross-camera near-duplicate pairs (shown side by side), "
            "and records with warnings.",
            "",
            "![suspicious](images/suspicious.jpg)",
            "",
        ]
    else:
        md += ["None.", ""]

    md += [
        "---",
        "",
        "Images: Caltech Camera Traps (CCT20), via LILA BC, Community Data License "
        "Agreement (permissive variant).",
        "",
    ]
    conn.close()
    out_dir.mkdir(parents=True, exist_ok=True)
    report = out_dir / "README.md"
    report.write_text("\n".join(md))
    return report
