"""initial schema

Revision ID: ec3dafdad4cc
Revises:
Create Date: 2026-09-24 17:57:09.863336
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "ec3dafdad4cc"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace", sa.String(length=100), nullable=False),
        sa.Column("request_key", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued', 'processing', 'completed', 'completed_with_errors', 'failed')",
            name=op.f("ck_batches_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_batches")),
        sa.UniqueConstraint(
            "workspace", "request_key", name=op.f("uq_batches_workspace_request_key")
        ),
    )
    op.create_table(
        "model_releases",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("is_test", sa.Boolean(), nullable=False),
        sa.Column("weights_key", sa.Text(), nullable=True),
        sa.Column("class_names", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("class_map_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("preprocessing", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("preprocessing_version", sa.String(length=64), nullable=False),
        sa.Column("calibration", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("policy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("policy_version", sa.String(length=100), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_releases")),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("camera_id", sa.String(length=200), nullable=True),
        sa.Column("grouping_rule", sa.String(length=100), nullable=False),
        sa.Column("group_key", sa.String(length=64), nullable=False),
        sa.Column("start_at", sa.DateTime(), nullable=True),
        sa.Column("end_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["batches.id"],
            name=op.f("fk_events_batch_id_batches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
        sa.UniqueConstraint("batch_id", "group_key", name=op.f("uq_events_batch_id_group_key")),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("model_release_id", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'succeeded', 'failed')", name=op.f("ck_jobs_status")
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"], ["batches.id"], name=op.f("fk_jobs_batch_id_batches"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["model_release_id"],
            ["model_releases.id"],
            name=op.f("fk_jobs_model_release_id_model_releases"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("batch_id", "kind", name=op.f("uq_jobs_batch_id_kind")),
    )
    op.create_table(
        "decisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("model_release_id", sa.String(length=100), nullable=False),
        sa.Column("policy_version", sa.String(length=100), nullable=False),
        sa.Column("disposition", sa.String(length=30), nullable=False),
        sa.Column("suggested_label", sa.String(length=100), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "disposition IN ('likely_empty', 'species_identified', 'needs_review')",
            name=op.f("ck_decisions_disposition"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_decisions_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["model_release_id"],
            ["model_releases.id"],
            name=op.f("fk_decisions_model_release_id_model_releases"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decisions")),
        sa.UniqueConstraint(
            "event_id",
            "model_release_id",
            "policy_version",
            name=op.f("uq_decisions_event_id_model_release_id_policy_version"),
        ),
    )
    op.create_table(
        "images",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("original_filename", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("storage_key", sa.Text(), nullable=True),
        sa.Column("content_type", sa.String(length=50), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("camera_id", sa.String(length=200), nullable=True),
        sa.Column("captured_at", sa.DateTime(), nullable=True),
        sa.Column("sequence_id", sa.String(length=200), nullable=True),
        sa.Column(
            "user_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("validation_status", sa.String(length=20), nullable=False),
        sa.Column("validation_error", sa.Text(), nullable=True),
        sa.Column("duplicate_of", sa.Uuid(), nullable=True),
        sa.Column("event_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "validation_status != 'invalid' OR validation_error IS NOT NULL",
            name=op.f("ck_images_error_reason"),
        ),
        sa.CheckConstraint(
            "validation_status IN ('pending', 'valid', 'invalid', 'duplicate')",
            name=op.f("ck_images_validation_status"),
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["batches.id"],
            name=op.f("fk_images_batch_id_batches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["duplicate_of"], ["images.id"], name=op.f("fk_images_duplicate_of_images")
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_images_event_id_events"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_images")),
        sa.UniqueConstraint("batch_id", "position", name=op.f("uq_images_batch_id_position")),
    )
    op.create_index(op.f("ix_images_event_id"), "images", ["event_id"], unique=False)
    op.create_index("ix_images_sha256", "images", ["sha256"], unique=False)
    op.create_table(
        "reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("reviewer", sa.String(length=200), nullable=False),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("suggested_label", sa.String(length=100), nullable=True),
        sa.Column("confirmed_label", sa.String(length=100), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("previous_review_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "outcome IN ('confirmed', 'corrected', 'unresolved')", name=op.f("ck_reviews_outcome")
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_reviews_event_id_events"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["previous_review_id"],
            ["reviews.id"],
            name=op.f("fk_reviews_previous_review_id_reviews"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviews")),
        sa.UniqueConstraint("previous_review_id", name=op.f("uq_reviews_previous_review_id")),
    )
    op.create_table(
        "predictions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("image_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=True),
        sa.Column("model_release_id", sa.String(length=100), nullable=False),
        sa.Column("class_probabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("suggested_label", sa.String(length=100), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_predictions_event_id_events"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["images.id"],
            name=op.f("fk_predictions_image_id_images"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["model_release_id"],
            ["model_releases.id"],
            name=op.f("fk_predictions_model_release_id_model_releases"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_predictions")),
        sa.UniqueConstraint(
            "image_id", "model_release_id", name=op.f("uq_predictions_image_id_model_release_id")
        ),
    )
    op.create_index(op.f("ix_predictions_event_id"), "predictions", ["event_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_predictions_event_id"), table_name="predictions")
    op.drop_table("predictions")
    op.drop_table("reviews")
    op.drop_index("ix_images_sha256", table_name="images")
    op.drop_index(op.f("ix_images_event_id"), table_name="images")
    op.drop_table("images")
    op.drop_table("decisions")
    op.drop_table("jobs")
    op.drop_table("events")
    op.drop_table("model_releases")
    op.drop_table("batches")
    # ### end Alembic commands ###
