"""review study

Revision ID: 75a20a6ff8c3
Revises: 25590cfa78af
Create Date: 2026-09-25 14:48:57.291799
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "75a20a6ff8c3"
down_revision: str | None = "25590cfa78af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "study_plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("protocol_sha256", sa.String(length=64), nullable=False),
        sa.Column("sets", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("truth", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_study_plans")),
    )
    op.create_table(
        "study_participants",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("arm", sa.Integer(), nullable=False),
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["study_plans.id"],
            name=op.f("fk_study_participants_plan_id_study_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_study_participants")),
        sa.UniqueConstraint("plan_id", "code", name=op.f("uq_study_participants_plan_id_code")),
    )
    op.create_table(
        "study_ratings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("participant", sa.String(length=50), nullable=False),
        sa.Column("block", sa.Integer(), nullable=False),
        sa.Column("condition", sa.String(length=20), nullable=False),
        sa.Column("difficulty", sa.Integer(), nullable=False),
        sa.CheckConstraint("difficulty BETWEEN 1 AND 5", name=op.f("ck_study_ratings_difficulty")),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["study_plans.id"],
            name=op.f("fk_study_ratings_plan_id_study_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_study_ratings")),
        sa.UniqueConstraint(
            "plan_id",
            "participant",
            "block",
            name=op.f("uq_study_ratings_plan_id_participant_block"),
        ),
    )
    op.create_table(
        "study_trials",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("participant", sa.String(length=50), nullable=False),
        sa.Column("block", sa.Integer(), nullable=False),
        sa.Column("condition", sa.String(length=20), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=True),
        sa.Column("seconds", sa.Float(), nullable=False),
        sa.Column("interactions", sa.Integer(), nullable=False),
        sa.Column("shown_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "condition IN ('grouped', 'suggested')", name=op.f("ck_study_trials_condition")
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["study_plans.id"],
            name=op.f("fk_study_trials_plan_id_study_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_study_trials")),
        sa.UniqueConstraint(
            "plan_id",
            "participant",
            "event_id",
            name=op.f("uq_study_trials_plan_id_participant_event_id"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("study_trials")
    op.drop_table("study_ratings")
    op.drop_table("study_participants")
    op.drop_table("study_plans")
    # ### end Alembic commands ###
