"""releases, leases, and processing errors

Revision ID: 5292ea38ade2
Revises: ec3dafdad4cc
Create Date: 2026-09-25 09:45:49.655638
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "5292ea38ade2"
down_revision: str | None = "ec3dafdad4cc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


IMMUTABLE_FUNCTION = """
CREATE FUNCTION forbid_release_update() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'model release % is immutable; register a new release instead', OLD.id;
END;
$$ LANGUAGE plpgsql
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "release_activations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("release_id", sa.String(length=100), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "activated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["model_releases.id"],
            name=op.f("fk_release_activations_release_id_model_releases"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_release_activations")),
    )
    op.add_column("images", sa.Column("processing_error", sa.Text(), nullable=True))
    op.add_column("jobs", sa.Column("lease_token", sa.Uuid(), nullable=True))
    op.add_column("jobs", sa.Column("worker_id", sa.String(length=200), nullable=True))
    op.add_column("jobs", sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("jobs", sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "model_releases", sa.Column("weights_sha256", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "model_releases",
        sa.Column(
            "provenance",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
    )
    op.add_column(
        "predictions",
        sa.Column(
            "calibrated_probabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###
    # Releases are immutable: a job pinned to one must always run the same thing.
    op.execute(IMMUTABLE_FUNCTION)
    op.execute(
        "CREATE TRIGGER model_releases_immutable BEFORE UPDATE ON model_releases "
        "FOR EACH ROW EXECUTE FUNCTION forbid_release_update()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS model_releases_immutable ON model_releases")
    op.execute("DROP FUNCTION IF EXISTS forbid_release_update()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("predictions", "calibrated_probabilities")
    op.drop_column("model_releases", "provenance")
    op.drop_column("model_releases", "weights_sha256")
    op.drop_column("jobs", "next_attempt_at")
    op.drop_column("jobs", "heartbeat_at")
    op.drop_column("jobs", "worker_id")
    op.drop_column("jobs", "lease_token")
    op.drop_column("images", "processing_error")
    op.drop_table("release_activations")
    # ### end Alembic commands ###
