"""audit sampling

Revision ID: 12c9bcb82636
Revises: 75a20a6ff8c3
Create Date: 2026-09-25 15:24:08.647476
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "12c9bcb82636"
down_revision: str | None = "75a20a6ff8c3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "decisions",
        sa.Column("audit_selected", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column("decisions", sa.Column("audit_rule", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("decisions", "audit_rule")
    op.drop_column("decisions", "audit_selected")
    # ### end Alembic commands ###
