"""How many events could this model label automatically at 95% precision?

A development-only feasibility bound for the v2 experiment, read from the
release's saved evaluation (`uv run wildinbox evaluate` writes it to
`<model>/eval/events.jsonl.gz`; the final test is not in it). For each
partition, events are ranked by the event's suggestion confidence and cut where
precision would still be >= 95%:

- `global`: one cutoff for every suggestion (any label, including empty);
- `per_class_point`: the best cutoff per suggested label, chosen in-sample, so
  an optimistic bound that would not fully replicate;
- `per_class_wilson`: the same, but the 95% Wilson lower bound must be >= 95%;
- `ceiling`: every correct suggestion accepted and nothing else (a perfect
  selector over this model's suggestions).

Coverage is always a share of *all* events in the partition, including
unsupported, vehicle, and mixed events, which can never be accepted correctly.

    uv run python scripts/coverage_frontier.py \\
        --events models/finetune-e3-deep-balanced/eval/events.jsonl.gz \\
        --out reports/adaptation/feasibility
"""

from __future__ import annotations

import argparse
import gzip
import json
from collections.abc import Callable
from pathlib import Path
from typing import Any

from wildinbox.evaluation.metrics import wilson

PARTITIONS = {
    "seen_camera_diagnostic": "Seen cameras (held-out sequences of training cameras)",
    "calibration": "Unseen: calibration cameras 51, 108",
    "policy_validation": "Unseen: policy-validation cameras 90, 125",
}
TARGET = 0.95


def _best_cut(events: list[dict[str, Any]], ok: Callable[[int, int], bool]) -> int:
    """Largest prefix (by confidence) whose correct/accepted passes `ok`."""
    ranked = sorted(events, key=lambda e: -e["confidence"])
    best = correct = 0
    for i, e in enumerate(ranked, 1):
        correct += e["suggested"] == e["label"]
        if ok(correct, i):
            best = i
    return best


def frontier(events: list[dict[str, Any]]) -> dict[str, Any]:
    n = len(events)
    suggested = [e for e in events if e.get("suggested")]
    classes = sorted({e["suggested"] for e in suggested})

    def point(k: int, i: int) -> bool:
        return k / i >= TARGET

    def lower(k: int, i: int) -> bool:
        return wilson(k, i)[0] >= TARGET

    by_class = {c: [e for e in suggested if e["suggested"] == c] for c in classes}
    per_point = {c: _best_cut(es, point) for c, es in by_class.items()}
    per_wilson = {c: _best_cut(es, lower) for c, es in by_class.items()}
    return {
        "events": n,
        "empty_share": sum(e["label"] == "empty" for e in events) / n,
        "global_point": _best_cut(suggested, point) / n,
        "global_wilson": _best_cut(suggested, lower) / n,
        "per_class_point": sum(per_point.values()) / n,
        "per_class_wilson": sum(per_wilson.values()) / n,
        "ceiling": sum(e.get("suggested") == e["label"] for e in events) / n,
        "per_class": {
            c: {"suggested": len(es), "point": per_point[c], "wilson": per_wilson[c]}
            for c, es in by_class.items()
        },
    }


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--events", type=Path, required=True)
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args()
    with gzip.open(args.events, "rt") as f:
        rows = [json.loads(line) for line in f]
    if any(r["partition"] not in PARTITIONS for r in rows):
        raise SystemExit("unexpected partition: only development partitions may be read")
    result = {p: frontier([r for r in rows if r["partition"] == p]) for p in PARTITIONS}
    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "frontier.json").write_text(json.dumps(result, indent=2) + "\n")

    def pct(x: float) -> str:
        return f"{100 * x:.1f}%"

    md = [
        "# Feasibility: automatic labels at 95% precision (development only)",
        "",
        f"Source: the released model's development evaluation (`{args.events}`), "
        "event suggestions and their uncalibrated confidence (a cutoff depends only on "
        "the ranking). The final test is not read. Generated by "
        "[`scripts/coverage_frontier.py`](../../../scripts/coverage_frontier.py); "
        "numbers in [`frontier.json`](frontier.json).",
        "",
        "Share of **all** events that could be labelled automatically while precision "
        "stays >= 95%:",
        "",
        "| Partition | Events | Empty | One cutoff | Per label, in-sample | "
        "Per label, lower bound | Perfect selector |",
        "|---|---|---|---|---|---|---|",
    ]
    for p, label in PARTITIONS.items():
        r = result[p]
        md.append(
            f"| {label} | {r['events']:,} | {pct(r['empty_share'])} | "
            f"{pct(r['global_point'])} | {pct(r['per_class_point'])} | "
            f"{pct(r['per_class_wilson'])} | {pct(r['ceiling'])} |"
        )
    md += [
        "",
        "- **One cutoff:** a single confidence threshold for every suggestion.",
        "- **Per label, in-sample:** the best threshold per suggested label, chosen on "
        "these same events, so optimistic.",
        "- **Per label, lower bound:** the 95% Wilson lower bound of precision must "
        "itself reach 95%, as the release rule requires.",
        "- **Perfect selector:** every correct suggestion accepted and nothing else; no "
        "threshold on this model can do better.",
        "",
        "## What this shows",
        "",
        "- On unseen cameras even a perfect selector over this model's suggestions "
        "labels under half the events, and no label passes the release rule's lower "
        "bound. The 50% review-reduction target cannot be met by tuning thresholds.",
        "- On cameras the model was trained on, the in-sample bound approaches but does "
        "not reach 50%. This is the most that adapting the model to a camera could "
        "plausibly deliver with this architecture, and it motivates the v2 experiment: "
        "adapt to each new camera from its first reviewed events, and accept labels only "
        "where that camera's precision holds.",
        "",
    ]
    (args.out / "README.md").write_text("\n".join(md))
    print(f"report -> {args.out / 'README.md'}")


if __name__ == "__main__":
    main()
